# Generated by Django 5.2 on 2026-05-26

from typing import ClassVar

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """Initial migration for Token model."""

    initial = True

    dependencies: ClassVar = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations: ClassVar = [
        migrations.CreateModel(
            name='Token',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        max_length=255,
                        verbose_name='Name',
                    ),
                ),
                (
                    'token_hash',
                    models.CharField(
                        max_length=64,
                        unique=True,
                        verbose_name='Token hash',
                    ),
                ),
                (
                    'expires_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='Expires at',
                    ),
                ),
                (
                    'revoked_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='Revoked at',
                    ),
                ),
                (
                    'last_used_at',
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name='Last used at',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Created at',
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name='Updated at',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='dmr_tokens',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
            },
        ),
    ]
