from dmr.plugins.pydantic import PydanticSerializer
from dmr.routing import Router, path
from dmr.security.jwt import concrete_views
from server.apps.jwt_auth import views

router = Router(
    'jwt-auth/',
    [
        path(
            'jwt-obtain-access-refresh-sync/',
            views.ObtainAccessAndRefreshSyncController.as_view(),
            name='jwt_obtain_access_refresh_sync',
        ),
        path(
            'jwt-obtain-access-refresh-async/',
            views.ObtainAccessAndRefreshAsyncController.as_view(),
            name='jwt_obtain_access_refresh_async',
        ),
        path(
            'jwt-refresh-sync/',
            views.RefreshSyncController.as_view(),
            name='jwt_refresh_sync',
        ),
        path(
            'jwt-refresh-async/',
            views.RefreshAsyncController.as_view(),
            name='jwt_refresh_async',
        ),
        path(
            'jwt-verify-sync/',
            views.VerifySyncController.as_view(),
            name='jwt_verify_sync',
        ),
        path(
            'jwt-verify-async/',
            views.VerifyAsyncController.as_view(),
            name='jwt_verify_async',
        ),
        path(
            'jwt-sync-auth/',
            views.ControllerWithJWTSyncAuth.as_view(),
            name='jwt_sync_auth',
        ),
        path(
            'jwt-async-auth/',
            views.ControllerWithJWTAsyncAuth.as_view(),
            name='jwt_async_auth',
        ),
        path(
            'jwt-cookie-sync-auth/',
            views.ControllerWithCookieJWTSyncAuth.as_view(),
            name='jwt_cookie_sync_auth',
        ),
        path(
            'jwt-cookie-async-auth/',
            views.ControllerWithCookieJWTAsyncAuth.as_view(),
            name='jwt_cookie_async_auth',
        ),
        path(
            'jwt-cookie-obtain-sync/',
            views.CookieObtainSyncController.as_view(),
            name='jwt_cookie_obtain_sync',
        ),
        path(
            'jwt-cookie-obtain-async/',
            views.CookieObtainAsyncController.as_view(),
            name='jwt_cookie_obtain_async',
        ),
        path(
            'jwt-cookie-obtain-body/',
            views.CookieObtainWithBodySyncController.as_view(),
            name='jwt_cookie_obtain_body',
        ),
        path(
            'jwt-cookie-refresh-sync/',
            views.CookieRefreshSyncController.as_view(),
            name='jwt_cookie_refresh_sync',
        ),
        path(
            'jwt-cookie-refresh-async/',
            views.CookieRefreshAsyncController.as_view(),
            name='jwt_cookie_refresh_async',
        ),
        path(
            'jwt-cookie-logout-sync/',
            views.CookieLogoutSyncView.as_view(),
            name='jwt_cookie_logout_sync',
        ),
        path(
            'jwt-cookie-logout-async/',
            views.CookieLogoutAsyncView.as_view(),
            name='jwt_cookie_logout_async',
        ),
        path(
            'jwt-concrete-obtain-sync/',
            concrete_views.ObtainTokensSyncController.as_view(
                serializer=PydanticSerializer,
            ),
            name='jwt_concrete_obtain_sync',
        ),
        path(
            'jwt-concrete-obtain-async/',
            concrete_views.ObtainTokensAsyncController.as_view(
                serializer=PydanticSerializer,
            ),
            name='jwt_concrete_obtain_async',
        ),
        path(
            'jwt-concrete-refresh-sync/',
            concrete_views.RefreshTokenSyncController.as_view(
                serializer=PydanticSerializer,
            ),
            name='jwt_concrete_refresh_sync',
        ),
        path(
            'jwt-concrete-refresh-async/',
            concrete_views.RefreshTokenAsyncController.as_view(
                serializer=PydanticSerializer,
            ),
            name='jwt_concrete_refresh_async',
        ),
        path(
            'jwt-concrete-verify-sync/',
            concrete_views.VerifyTokenSyncController.as_view(
                serializer=PydanticSerializer,
            ),
            name='jwt_concrete_verify_sync',
        ),
        path(
            'jwt-concrete-verify-async/',
            concrete_views.VerifyTokenAsyncController.as_view(
                serializer=PydanticSerializer,
            ),
            name='jwt_concrete_verify_async',
        ),
        path(
            'jwt-concrete-cookie-obtain-sync/',
            concrete_views.CookieObtainTokensSyncController.as_view(
                serializer=PydanticSerializer,
            ),
            name='jwt_concrete_cookie_obtain_sync',
        ),
        path(
            'jwt-concrete-cookie-obtain-async/',
            concrete_views.CookieObtainTokensAsyncController.as_view(
                serializer=PydanticSerializer,
            ),
            name='jwt_concrete_cookie_obtain_async',
        ),
        path(
            'jwt-concrete-cookie-refresh-sync/',
            concrete_views.CookieRefreshTokensSyncController.as_view(
                serializer=PydanticSerializer,
            ),
            name='jwt_concrete_cookie_refresh_sync',
        ),
        path(
            'jwt-concrete-cookie-refresh-async/',
            concrete_views.CookieRefreshTokensAsyncController.as_view(
                serializer=PydanticSerializer,
            ),
            name='jwt_concrete_cookie_refresh_async',
        ),
        path(
            'jwt-concrete-cookie-logout-sync/',
            concrete_views.CookieLogoutSyncController.as_view(
                serializer=PydanticSerializer,
            ),
            name='jwt_concrete_cookie_logout_sync',
        ),
        path(
            'jwt-concrete-cookie-logout-async/',
            concrete_views.CookieLogoutAsyncController.as_view(
                serializer=PydanticSerializer,
            ),
            name='jwt_concrete_cookie_logout_async',
        ),
    ],
    tags=['jwt_auth'],
)
