require_https = true
include_fragments = "full"
cache = true
remap = [
  # TODO: remove when this is fixed https://github.com/lycheeverse/lychee/issues/1729
  "https://github.com/(.*?)/(.*?)/blob/(.*?)/(.*#.*)$ https://raw.githubusercontent.com/$1/$2/$3/$4",
]
exclude = [
  # This is way too flaky https://github.com/lycheeverse/lychee/issues/1884
  '^https://toml.io/.*',
  # TODO: remove when this is fixed https://github.com/pradyunsg/furo/issues/907
  '^http://github\.com/cferdinandi/gumshoe$',
  "^http://localhost",
  "^https://localhost",
  "^mailto:",
]

exclude_path = ["CHANGELOG.md"]

accept = [200, 403, 429]

max_retries = 3
retry_wait_time = 2
timeout = 20
insecure = false
verbose = true
scheme = ["https"]
