version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: '3.13'
  jobs:
    pre_install:
      - uv export
        --all-extras
        --group docs
        --no-emit-project
        --format=requirements.txt
        --output-file=requirements.txt

python:
  install:
    - method: uv
      command: pip
      requirements: requirements.txt

sphinx:
  configuration: 'docs/conf.py'
  fail_on_warning: true
