[generation]
# Limit the number of generated examples per API operation to keep tests fast.
max-examples = 100

[warnings]
# Fail on any warning:
fail-on = true

[auth.openapi.http_basic]
username = 'test'
password = 'pass'

[auth.dynamic.openapi.jwt]
path = '/api/jwt-auth/jwt-obtain-access-refresh-sync/'
# These are default user credentials from
# https://github.com/pytest-dev/pytest-django
payload = { username = 'admin', password = 'password' }
extract_selector = '/access_token'

[output.sanitization]
# We don't have any real data to hide, but it is easier to debug:
enabled = false
