import contextlib
import dataclasses
from collections.abc import Awaitable, Generator
from http import HTTPStatus
from typing import TYPE_CHECKING, Any, ClassVar, TypeVar

from django.http import HttpResponse, HttpResponseBase
from django.test import AsyncClient, AsyncRequestFactory, Client, RequestFactory

from dmr.internal.json import json_dump, json_loads
from dmr.throttling import AsyncThrottle, SyncThrottle

if TYPE_CHECKING:
    from dmr.controller import Controller
    from dmr.serializer import BaseSerializer

_ThingT = TypeVar('_ThingT')

#: Expected value for a header checked by ``assert_throttled``: an ``int``
#: (rendered to its ``str`` form), a ``str``, or a matcher like
#: ``dirty_equals.IsStr``. Typed as ``object`` because the header is compared
#: with ``==``, so no narrower static type is correct -- matchers like
#: ``IsStr`` are deliberately unhashable, so a ``Protocol`` won't help.
_HeaderValue = object


class _DMRMixin:  # noqa: WPS338
    default_content_type: ClassVar[str] = 'application/json'

    def _encode_json(self, data: Any, content_type: str) -> Any:
        should_encode = (
            content_type == self.default_content_type
            and not isinstance(data, (str, bytes))
        )
        return json_dump(data) if should_encode else data

    def _parse_json(self, response: HttpResponse, **extra: Any) -> Any:
        # This implementation mirrors Django's response JSON parsing
        # behavior instead of introducing a cleaner local abstraction.
        #
        # We keep it close to Django on purpose:
        # - it caches the parsed value on `response._json`
        # - it validates the response `Content-Type` before parsing
        # - it parses `response.content` and decodes it
        #   using the response charset before JSON deserialization
        #
        # It preserving Django-compatible behavior here is
        # more important than improving the internal style of this helper.
        if not hasattr(response, '_json'):
            if response.get('Content-Type') != self.default_content_type:
                raise ValueError(  # pragma: no cover
                    f'Content-Type header is "{response.get("Content-Type")}", '
                    f'not "{self.default_content_type}"',
                )

            response._json = json_loads(  # type: ignore[attr-defined]  # noqa: SLF001
                # Copies Django<5.2 behavior for older versions of Django:
                response.content.decode(response.charset or 'utf8'),
                **extra,
            )
        return response._json  # type: ignore[attr-defined]  # noqa: SLF001

    if TYPE_CHECKING:  # noqa: WPS604  # pragma: no cover

        def _encode_data(
            self,
            data: dict[str, Any],
            content_type: str,
        ) -> bytes: ...

    else:  # pragma: no cover
        # This code is autogenerated, please do not touch it.
        # It lives under `if not TYPE_CHECKING` so it would not ruin
        # typing done by `django-stubs`.
        # ALL THIS CODE DOES IS JUST A DEFAULT CONTENT_TYPE CHANGE, WTF!

        def post(self, path, data='', content_type=None, *args, **kwargs):
            if content_type is None:
                content_type = self.default_content_type
            return super().post(path, data, content_type, *args, **kwargs)

        def options(self, path, data='', content_type=None, *args, **kwargs):
            if content_type is None:
                content_type = self.default_content_type
            return super().options(path, data, content_type, *args, **kwargs)

        def put(self, path, data='', content_type=None, *args, **kwargs):
            if content_type is None:
                content_type = self.default_content_type
            return super().put(path, data, content_type, *args, **kwargs)

        def patch(self, path, data='', content_type=None, *args, **kwargs):
            if content_type is None:
                content_type = self.default_content_type
            return super().patch(path, data, content_type, *args, **kwargs)

        def delete(self, path, data='', content_type=None, *args, **kwargs):
            if content_type is None:
                content_type = self.default_content_type
            return super().delete(path, data, content_type, *args, **kwargs)

        def generic(
            self,
            method,
            path,
            data='',
            content_type=None,
            *args,
            **kwargs,
        ):
            if isinstance(self, AsyncRequestFactory) or content_type is None:
                # See https://github.com/django/django/commit/caf90a971f09323775ed0cacf94eadaf39d040e0
                # Django versions 5.2.12 and 5.2.13 behave differently now:
                headers = kwargs.get('headers', {}) or {}
                content_type = (
                    headers.pop(
                        'Content-Type',
                        self.default_content_type,
                    )
                    if isinstance(self, AsyncRequestFactory)
                    else headers.get(
                        'Content-Type',
                        self.default_content_type,
                    )
                )
            return super().generic(
                method,
                path,
                data,
                content_type,
                *args,
                **kwargs,
            )


class DMRRequestFactory(_DMRMixin, RequestFactory):
    """
    Test utility for testing apps using ``django-modern-rest``.

    Based on :class:`django.test.RequestFactory`.
    See their docs for advanced usage:
    https://docs.djangoproject.com/en/dev/topics/testing/tools

    This type, in contrast to a regular ``RequestFactory``,
    sets ``content-type`` as ``application/json``.

    Sets WSGI environment.
    """


class DMRAsyncRequestFactory(_DMRMixin, AsyncRequestFactory):
    """
    Version of :class:`DMRRequestFactory` but for ASGI environment.

    Uses the exactly the same API.
    """

    if TYPE_CHECKING:  # noqa: WPS604

        def wrap(self, thing: _ThingT) -> Awaitable[_ThingT]:  # pyright: ignore[reportReturnType]  # pyrefly: ignore [bad-return]
            """Does nothing."""

    else:

        def wrap(self, thing):
            """
            Utility method for testing.

            Pretends to wrap async controllers into async functions for typing.
            But in reality does nothing.

            This happens due to the fact that ``View`` is typed as sync object.
            """
            return thing


class DMRClient(_DMRMixin, Client):
    """
    Test utility for testing apps using ``django-modern-rest``.

    Based on :class:`django.test.Client`.
    See their docs for advanced usage:
    https://docs.djangoproject.com/en/dev/topics/testing/tools/

    This type, in contrast to a regular ``Client``,
    sets ``content-type`` as ``application/json``.
    """


class DMRAsyncClient(_DMRMixin, AsyncClient):
    """
    Async version of :class:`DMRClient`.

    Uses ``async`` API.
    Requires you to ``await`` calls to ``.get``, ``.post``, etc.
    """


@contextlib.contextmanager
def reduced_throttling(
    controller_cls: 'type[Controller[BaseSerializer]]',
    *,
    method: str = 'GET',
    max_requests: int = 2,
) -> Generator[SyncThrottle | AsyncThrottle, None, None]:
    """
    Temporarily lower an endpoint's first throttle to ``max_requests``.

    A few real requests then reach the limit instead of the configured rate.
    Only the endpoint under test is affected; throttling is restored on exit.

    .. versionadded:: 0.12.0
    """
    endpoint = controller_cls.api_endpoints.get(method.upper())
    if endpoint is None:
        raise ValueError(
            f'{controller_cls.__qualname__} has no endpoint '
            f'for method {method!r}',
        )
    metadata = endpoint.metadata
    throttles = metadata.throttling
    if not throttles:
        raise ValueError(
            f'Endpoint {metadata.operation_id} has no throttling to test',
        )

    original = throttles[0]
    reduced = original.replace(max_requests=max_requests)
    # Swap the throttle in a fresh metadata; restored in `finally` below:
    endpoint.metadata = dataclasses.replace(
        metadata,
        throttling_before_auth=_swap(
            metadata.throttling_before_auth,
            original,
            reduced,
        ),
        throttling_after_auth=_swap(
            metadata.throttling_after_auth,
            original,
            reduced,
        ),
    )
    try:
        yield reduced
    finally:
        endpoint.metadata = metadata


def _swap(
    throttles: 'tuple[SyncThrottle | AsyncThrottle, ...] | None',
    old: 'SyncThrottle | AsyncThrottle',
    new: 'SyncThrottle | AsyncThrottle',
) -> 'tuple[SyncThrottle | AsyncThrottle, ...] | None':
    if not throttles:
        return throttles
    return tuple(new if throttle is old else throttle for throttle in throttles)


def assert_throttled(
    response: HttpResponse,
    *,
    limit: _HeaderValue | None = None,
    reset: _HeaderValue | None = None,
    retry_after: _HeaderValue | None = None,
    detail: bool = True,
) -> None:
    """
    Assert that a response was rejected by throttling.

    Collapses the repeated ``429`` status, header and error-body checks into
    a single call::

        assert_throttled(response)  # just the status + `ratelimit` error
        assert_throttled(response, limit=5, reset=1, retry_after=1)

    Parameters:
        response: The response to check.
        limit: Expected ``X-RateLimit-Limit`` header, when given.
        reset: Expected ``X-RateLimit-Reset`` header, when given.
        retry_after: Expected ``Retry-After`` header, when given.
        detail: Also assert the body is a ``ratelimit`` error. ``True``
            by default; set to ``False`` for custom error models.

    Header expectations accept an ``int`` (matched as its string form), a
    ``str``, or any matcher object (e.g. ``dirty_equals.IsStr()``) for
    real-time tests where the exact reset value is unknown.

    .. versionadded:: 0.12.0
    """
    assert response.status_code == HTTPStatus.TOO_MANY_REQUESTS, (
        response.content
    )
    _assert_header(response.headers, 'X-RateLimit-Limit', limit)
    _assert_header(response.headers, 'X-RateLimit-Reset', reset)
    _assert_header(response.headers, 'Retry-After', retry_after)
    if detail:
        _assert_ratelimit_detail(response)


def _assert_header(
    headers: Any,
    name: str,
    expected: _HeaderValue | None,
) -> None:
    if expected is None:
        return
    if isinstance(expected, int):
        expected = str(expected)
    present = dict(headers)
    assert name in headers, (
        f'Header {name!r} is missing, present headers: {present!r}'
    )
    actual = headers[name]
    assert actual == expected, (
        f'Header {name!r}: expected {expected!r}, got {actual!r}'
    )


def _assert_ratelimit_detail(response: HttpResponse) -> None:
    body = json_loads(response.content.decode(response.charset or 'utf8'))
    problems = body['detail']
    assert problems, (
        f'Expected a non-empty `detail` in throttled response, got {body!r}'
    )
    assert all(problem.get('type') == 'ratelimit' for problem in problems), body


def _as_response(candidate: HttpResponseBase) -> HttpResponse:
    assert isinstance(candidate, HttpResponse), candidate
    return candidate


def _assert_ok(candidate: HttpResponseBase) -> None:
    response = _as_response(candidate)
    assert response.status_code == HTTPStatus.OK, response.content


def assert_throttling(
    controller_cls: 'type[Controller[BaseSerializer]]',
    request_factory: DMRRequestFactory,
    path: str,
    *,
    method: str = 'GET',
    max_requests: int = 2,
    limit: _HeaderValue | None = None,
) -> HttpResponse:
    """
    Reduce the first throttle, drive requests, and assert the ``429``.

    Sends ``max_requests`` allowed requests, then one that is rejected, and
    checks it with :func:`assert_throttled`. Returns the ``429`` response so
    you can make further header assertions on it.

    .. versionadded:: 0.12.0
    """
    view = controller_cls.as_view()
    build = getattr(request_factory, method.lower())
    with reduced_throttling(
        controller_cls,
        method=method.upper(),
        max_requests=max_requests,
    ):
        for _ in range(max_requests):
            _assert_ok(view(build(path)))
        throttled = _as_response(view(build(path)))
    assert_throttled(throttled, limit=limit)
    return throttled


async def assert_async_throttling(
    controller_cls: 'type[Controller[BaseSerializer]]',
    request_factory: DMRAsyncRequestFactory,
    path: str,
    *,
    method: str = 'GET',
    max_requests: int = 2,
    limit: _HeaderValue | None = None,
) -> HttpResponse:
    """
    Async version of :func:`assert_throttling`.

    .. versionadded:: 0.12.0
    """
    view = controller_cls.as_view()
    build = getattr(request_factory, method.lower())
    with reduced_throttling(
        controller_cls,
        method=method.upper(),
        max_requests=max_requests,
    ):
        for _ in range(max_requests):
            _assert_ok(await request_factory.wrap(view(build(path))))  # noqa: WPS476
        throttled = _as_response(await request_factory.wrap(view(build(path))))
    assert_throttled(throttled, limit=limit)
    return throttled
