# Generated by Django 5.2.14 on 2026-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('model_simple', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursorPaginatedTestModel',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('increment_id', models.IntegerField()),
            ],
        ),
    ]
