# Generated by Django 5.2.12 on 2026-03-22 11:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('blocklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocklistedjwtoken',
            options={
                'verbose_name': 'BlocklistedJWToken',
                'verbose_name_plural': 'BlocklistedJWTokens',
            },
        ),
    ]
