# Generated by Django 5.2.16 on 2026-07-29 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import dmr.security.token.auth.base


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomToken',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'owner',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='custom_tokens',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(dmr.security.token.token.TokenLikeSync, models.Model),
        ),
    ]
