import datetime
from typing import Final, TypeAlias

import pytest
from django.urls import path, register_converter

from dmr import Controller
from dmr.openapi import build_schema
from dmr.openapi.mappers.schema_normalization import DumpedSchema
from dmr.plugins.pydantic import PydanticSerializer
from dmr.routing import Router
from dmr.serializer import BaseSerializer

_Serializers: TypeAlias = list[type[BaseSerializer]]
serializers: Final[_Serializers] = [
    PydanticSerializer,
]

try:
    from dmr.plugins.msgspec import MsgspecSerializer
except ImportError:  # pragma: no cover
    pass  # noqa: WPS420
else:  # pragma: no cover
    serializers.append(MsgspecSerializer)


class _DateConverter:
    """Custom converter that knows its own schema type."""

    regex = r'\d{4}-\d{2}-\d{2}'
    __dmr_converter_schema__ = datetime.date

    def to_python(self, value: str) -> datetime.date:  # noqa: WPS110
        raise NotImplementedError

    def to_url(self, value: datetime.date) -> str:  # noqa: WPS110
        raise NotImplementedError


register_converter(_DateConverter, 'dmr_test_date')


def _get_path_parameter(
    url_pattern: str,
    serializer: type[BaseSerializer],
) -> DumpedSchema:
    class _PathController(
        Controller[serializer],  # type: ignore[valid-type]
    ):
        def get(self) -> str:
            raise NotImplementedError

    schema = build_schema(
        Router('api/', [path(url_pattern, _PathController.as_view())]),
    ).convert()
    param_specs: list[DumpedSchema] = schema['paths']['/api/{param}/']['get'][
        'parameters'
    ]

    assert len(param_specs) == 1, param_specs
    return param_specs[0]


def _without_title(param_schema: DumpedSchema) -> DumpedSchema:
    # `title` is generated by a serializer, it is not our concern here:
    return {
        schema_key: schema_value
        for schema_key, schema_value in param_schema.items()
        if schema_key != 'title'
    }


@pytest.mark.parametrize('serializer', serializers)
@pytest.mark.parametrize(
    ('url_pattern', 'param_schema'),
    [
        ('<int:param>/', {'type': 'integer'}),
        ('<uuid:param>/', {'type': 'string', 'format': 'uuid'}),
        ('<str:param>/', {'type': 'string'}),
        (
            '<slug:param>/',
            {'type': 'string', 'pattern': '^[-a-zA-Z0-9_]+$'},
        ),
        (
            '<path:param>/',
            {'type': 'string', 'description': 'Can contain slashes'},
        ),
        ('<dmr_test_date:param>/', {'type': 'string', 'format': 'date'}),
    ],
)
def test_path_converter_schema(
    url_pattern: str,
    param_schema: DumpedSchema,
    *,
    serializer: type[BaseSerializer],
) -> None:
    """Ensures that django url converters have the correct schemas."""
    parameter = _get_path_parameter(url_pattern, serializer)

    assert parameter['name'] == 'param'
    assert parameter['in'] == 'path'
    assert parameter['required']
    assert _without_title(parameter['schema']) == param_schema
