name: CodSpeed

on:
  push:
    branches:
      - master
  pull_request:
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        persist-credentials: false

    - name: Set up Python 3.13
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install poetry
      run: |
        curl -sSL "https://install.python-poetry.org" | python

        # Adding `poetry` to `$PATH`:
        echo "$HOME/.poetry/bin" >> "$GITHUB_PATH"

    - name: Install dependencies
      run: |
        poetry config virtualenvs.in-project true
        poetry run pip install -U pip
        poetry install --all-extras --all-groups

    - name: Run benchmarks
      uses: CodSpeedHQ/action@v4
      with:
        mode: simulation
        run: poetry run pytest benchmarks/test_benchmarks.py -o "addopts=" --codspeed
