name: test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
        redis-image: ['redis:8-alpine']
        just-recipy: ['test']
        include:
          - python-version: '3.14t'
            redis-image: 'redis:7-alpine'
            force-free-gil: true
          - python-version: '3.13'
            redis-image: 'valkey/valkey:9-alpine'
          # Integration tests with different databases.
          - python-version: '3.13'
            redis-image: redis:8-alpine
            just-recipy: test_postgres
          - python-version: '3.13'
            redis-image: redis:8-alpine
            just-recipy: test_mysql

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@bec219d24cd3e171d82865faccec33120bb574f4 # v10.1.0

    - name: Install just
      run: uv tool install rust-just

    - name: Install dependencies
      run: |
        # System deps:
        sudo apt update && sudo apt install -y gettext default-libmysqlclient-dev gcc libpq-dev

        # Python deps:
        just install-integration
        # We don't install `orjson` in `pyproject.toml`,
        # because we run `3.14t` as well and it cannot be installed there :(
        # No way to exclude the platform on a file level.
        uv pip install orjson || true

    - name: Prefetch redis image
      if: ${{ matrix.redis-image }}
      run: docker pull "${{ matrix.redis-image }}"

    - name: Run checks
      run: just ${{ matrix.just-recipy || 'test' }}
      env:
        PYTHON_GIL: ${{ matrix.force-free-gil && '0' || '1' }}
        REDIS_IMAGE: ${{ matrix.redis-image }}

    # Upload coverage to codecov: https://codecov.io/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@0b35c9ecc4f0529d0eb674914510c22f85b196b4 # v7.1.0
      with:
        files: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Tracecov report
      run: cat tracecov-report.md >> "$GITHUB_STEP_SUMMARY"
